stages:
  - test
  - build

variables:
  FLASK_ENV: testing  # 테스트 환경 변수
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"  # 캐싱 설정

cache:
  paths:
    - .pip_cache/

test:
  stage: test
  image: python:3.9  # Python 이미지 선택
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest  # 테스트 실행
  only:
    - main

build:
  stage: build
  image: python:3.9
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python setup.py build  # 빌드 작업
  only:
    - main
